# Generated by Django 4.1 on 2022-08-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_no', models.AutoField(primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=255)),
                ('b_note', models.CharField(blank=True, max_length=4096, null=True)),
                ('b_writer', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_no', models.IntegerField(blank=True, null=True)),
                ('b_cout', models.IntegerField(blank=True, null=True)),
                ('b_date', models.DateTimeField(blank=True, null=True)),
                ('usage_flag', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
    ]
